spring:
  application:
    name: ex03
    #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/ex03
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出
    map-underscore-to-camel-case: true #开启驼峰命名
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itheima.pojo
#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug